# This is a basic workflow to help you get started with Actions

name: CI
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  main:
    runs-on: ubuntu-latest
    services:
      selenium:
        image: selenium/standalone-chrome
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.7
        uses: actions/setup-python@v2
        with:
          python-version: 3.7
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pipenv
          pipenv install
      - name: Prepare Selenium
      # https://github.com/marketplace/actions/setup-chromedriver
        uses: nanasess/setup-chromedriver@master
      - name: Install modules
        run: pipenv run pip install pandas lxml 
      # Runs a single command using the runners shell
      - name: Run main
        run: pipenv run python main.py
      - name: Upload
        uses: actions/upload-artifact@v2
        with:
          name: test.csv
          path: test.csv
        
